version: "3.7"
services:
  api:
      build: .
      ports:
        - 8000:80
      depends_on:
        - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  redis_admin:
    image: faktiva/php-redis-admin
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 4935:80

networks:        
  default:
      external:
          name: testing