apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-redis
  namespace: dotnet-redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnet-redis
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50