apiVersion: v1
kind: Service
metadata:
  name: redis-admin
  namespace: dotnet-redis
  namespace: dotnet-redis
spec:
  type: NodePort
  selector:
    app: redis-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80